version: "3.8"
services:
    apache_server:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: klaxoon_apache_server
        ports:
        -   "9080:80"
        volumes:
        -   "./:/var/www/klaxoon"
        -   "./apache-conf/klaxoon-api.conf:/etc/apache2/sites-available/klaxoon-api.conf"

    mysql:
        image: mysql:5.7
        container_name: klaxoon_mysql_server
        ports:
            - "9306:3306"
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
